const bank={
1:{title:"Kaixo!",subtitle:"Salutacions i comiat",objective:"Saluda, acomiada't, dona les gràcies i demana disculpes.",words:[["Kaixo","Hola"],["Agur","Adéu"],["Egun on","Bon dia"],["Arratsalde on","Bona tarda"],["Gabon","Bona nit"],["Eskerrik asko","Gràcies"],["Mesedez","Si us plau"],["Barkatu","Perdó"],["Ikusi arte","Fins aviat"],["Ongi etorri","Benvingut"]],situations:[["Arribes al matí i saludes.","Egun on"],["Et despedeixes.","Agur"],["Algú t'ajuda.","Eskerrik asko"],["Demanes una cosa educadament.","Mesedez"],["Et vols disculpar.","Barkatu"],["Arribes a la nit.","Gabon"],["Marxes dient que us veureu aviat.","Ikusi arte"],["Arribes i dius hola.","Kaixo"],["Dones la benvinguda.","Ongi etorri"],["Saludes a la tarda.","Arratsalde on"]]},
2:{title:"Ni… naiz",subtitle:"Presentar-se",objective:"Presenta't i pregunta qui és una persona.",words:[["Ni","Jo"],["Zu","Tu"],["Hura","Ell/ella"],["Gu","Nosaltres"],["Zuek","Vosaltres"],["Nor","Qui"],["Zer","Què"],["Izena","Nom"],["Naiz","Soc"],["Zara","Ets"]],situations:[["Parles de tu.","Ni"],["Parles directament amb algú.","Zu"],["Parles de vosaltres.","Zuek"],["Parles de nosaltres.","Gu"],["Preguntes qui és algú.","Nor"],["Preguntes què és una cosa.","Zer"],["Parles del nom.","Izena"],["Dius 'soc'.","Naiz"],["Dius 'ets'.","Zara"],["Parles d'una tercera persona.","Hura"]]},
3:{title:"Bai / Ez",subtitle:"Afirmar i negar",objective:"Aprèn a afirmar, negar, dubtar i confirmar.",words:[["Bai","Sí"],["Ez","No"],["Ez dakit","No ho sé"],["Agian","Potser"],["Ados","D'acord"],["Noski","És clar"],["Egia","Veritat"],["Oker","Incorrecte"],["Bada","Doncs sí"],["Ez da","No és"]],situations:[["Acceptes una proposta.","Bai"],["Rebutges una proposta.","Ez"],["No coneixes la resposta.","Ez dakit"],["No estàs segur.","Agian"],["Mostres conformitat.","Ados"],["Confirmes una cosa evident.","Noski"],["Parles de la veracitat.","Egia"],["Dius que una resposta no és correcta.","Oker"],["Confirmes amb 'doncs sí'.","Bada"],["Negues que una cosa sigui així.","Ez da"]]},
4:{title:"Cortesia bàsica",subtitle:"Expressions del dia a dia",objective:"Utilitza expressions de cortesia amb naturalitat.",words:[["Eskerrik asko","Gràcies"],["Mila esker","Moltes gràcies"],["Mesedez","Si us plau"],["Barkatu","Perdó"],["Aizu","Escolta / Ei"],["Ongi","Bé"],["Oso ondo","Molt bé"],["Ez horregatik","De res"],["Barkatu, mesedez","Perdona, si us plau"],["Agur bero bat","Una salutació afectuosa"]],situations:[["Dones les gràcies.","Eskerrik asko"],["Dones moltes gràcies.","Mila esker"],["Demanes una cosa amb educació.","Mesedez"],["Et disculpes.","Barkatu"],["Crides l'atenció d'algú.","Aizu"],["Respons que estàs bé.","Ongi"],["Dius que una cosa està molt bé.","Oso ondo"],["Respons a 'gràcies' amb 'de res'.","Ez horregatik"],["Et disculpes i demanes alguna cosa.","Barkatu, mesedez"],["T'acomiades amb afecte.","Agur bero bat"]]},
5:{title:"Repàs!",subtitle:"Situacions quotidianes",objective:"Combina les expressions bàsiques en situacions reals.",words:[["Kaixo","Hola"],["Agur","Adéu"],["Eskerrik asko","Gràcies"],["Mesedez","Si us plau"],["Barkatu","Perdó"],["Bai","Sí"],["Ez","No"],["Egun on","Bon dia"],["Gabon","Bona nit"],["Ongi etorri","Benvingut"]],situations:[["Arribes al matí.","Egun on"],["Saludes simplement.","Kaixo"],["Marxes.","Agur"],["Algú t'ajuda.","Eskerrik asko"],["Demanes una cosa.","Mesedez"],["Et disculpes.","Barkatu"],["Acceptes.","Bai"],["Rebutges.","Ez"],["Arribes a la nit.","Gabon"],["Dones la benvinguda.","Ongi etorri"]]},
6:{title:"Zenbakiak",subtitle:"Números 1–10",objective:"Aprèn els primers números.",words:[["bat","1"],["bi","2"],["hiru","3"],["lau","4"],["bost","5"],["sei","6"],["zazpi","7"],["zortzi","8"],["bederatzi","9"],["hamar","10"]],situations:[["Vols dir 1.","bat"],["Vols dir 2.","bi"],["Vols dir 3.","hiru"],["Vols dir 4.","lau"],["Vols dir 5.","bost"],["Vols dir 6.","sei"],["Vols dir 7.","zazpi"],["Vols dir 8.","zortzi"],["Vols dir 9.","bederatzi"],["Vols dir 10.","hamar"]]},
7:{title:"Etxea",subtitle:"La casa",objective:"Identifica espais i objectes bàsics de la llar.",words:[["etxea","Casa"],["atea","Porta"],["leihoa","Finestra"],["mahaia","Taula"],["aulkia","Cadira"],["ohea","Llit"],["sukaldea","Cuina"],["bainugela","Bany"],["egongela","Sala d'estar"],["gela","Habitació"]],situations:[["Parles de la llar.","etxea"],["Obres una entrada.","atea"],["Obres una obertura per on entra llum.","leihoa"],["Poses el menjar sobre això.","mahaia"],["T'hi asseus.","aulkia"],["Hi dorms.","ohea"],["Hi cuines.","sukaldea"],["Hi ha dutxa i lavabo.","bainugela"],["Mires la televisió en aquesta estança.","egongela"],["Dorms o treballes en aquesta estança.","gela"]]},
8:{title:"Familia",subtitle:"La família",objective:"Parla dels membres més propers de la família.",words:[["ama","Mare"],["aita","Pare"],["anaia","Germà"],["arreba","Germana"],["semea","Fill"],["alaba","Filla"],["amona","Àvia"],["aitona","Avi"],["osaba","Oncle"],["izeba","Tieta"]],situations:[["Parles de la teva mare.","ama"],["Parles del teu pare.","aita"],["Parles del teu germà.","anaia"],["Parles de la teva germana.","arreba"],["Parles del teu fill.","semea"],["Parles de la teva filla.","alaba"],["Parles de la teva àvia.","amona"],["Parles del teu avi.","aitona"],["Parles del teu oncle.","osaba"],["Parles de la teva tieta.","izeba"]]},
9:{title:"Koloreak",subtitle:"Els colors",objective:"Reconeix els colors més habituals.",words:[["gorria","Vermell"],["urdina","Blau"],["berdea","Verd"],["horia","Groc"],["beltza","Negre"],["zuria","Blanc"],["laranja","Taronja"],["morea","Lila"],["arrosa","Rosa"],["marroia","Marró"]],situations:[["Vols dir vermell.","gorria"],["Vols dir blau.","urdina"],["Vols dir verd.","berdea"],["Vols dir groc.","horia"],["Vols dir negre.","beltza"],["Vols dir blanc.","zuria"],["Vols dir taronja.","laranja"],["Vols dir lila.","morea"],["Vols dir rosa.","arrosa"],["Vols dir marró.","marroia"]]},
10:{title:"Egunerokoa",subtitle:"El dia a dia",objective:"Parla de moments del dia i de freqüència.",words:[["gaur","Avui"],["bihar","Demà"],["atzo","Ahir"],["orain","Ara"],["gero","Després"],["goizean","Al matí"],["arratsaldean","A la tarda"],["gauean","A la nit"],["beti","Sempre"],["inoiz ez","Mai"]],situations:[["Parles d'avui.","gaur"],["Parles de demà.","bihar"],["Parles d'ahir.","atzo"],["Parles del moment actual.","orain"],["Parles d'una acció posterior.","gero"],["Parles del matí.","goizean"],["Parles de la tarda.","arratsaldean"],["Parles de la nit.","gauean"],["Una cosa passa sempre.","beti"],["Una cosa no passa mai.","inoiz ez"]]}
};
function shuffle(a){return [...a].sort(()=>Math.random()-0.5)}
function opts(correct,pool){return shuffle([correct,...shuffle(pool.filter(x=>x!==correct)).slice(0,2)])}
function makeQuestions(l){const pool=l.words.map(x=>x[1]),eus=l.words.map(x=>x[0]),q=[];l.words.forEach(([eu,ca])=>q.push({type:'vocab',q:`Què vol dir «${eu}»?`,a:opts(ca,pool),correct:ca}));l.words.forEach(([eu,ca])=>q.push({type:'recall',q:`Com es diu «${ca}» en euskera?`,a:opts(eu,eus),correct:eu}));l.situations.forEach(([text,correct])=>q.push({type:'situation',q:text,a:opts(correct,eus),correct}));return q}
const lessons=Object.fromEntries(Object.entries(bank).map(([id,l])=>[id,{...l,questions:makeQuestions(l)}]));
let state=JSON.parse(localStorage.getItem('kaixoState')||'{"points":0,"done":[],"streak":0,"last":""}');let cur=null;const $=id=>document.getElementById(id),home=$("home"),lesson=$("lesson");
function save(){localStorage.setItem('kaixoState',JSON.stringify(state));updateHome()}
function updateHome(){$("points").textContent=state.points;$('done').textContent=state.done.length;$('streak').textContent=state.streak;const levels=$('levels');levels.innerHTML='';[[1,'A1 · Hasiberria','10 lliçons · 300 preguntes',true],[2,'A2 · Intermedi','Desbloqueja completant A1',state.done.length>=10],[3,'B1 · Intermedi avançat','Desbloqueja completant A2',false]].forEach(x=>{const b=document.createElement('button');b.className='level-card '+(x[3]?'active':'locked');b.disabled=!x[3];b.innerHTML=`<span class="badge">${x[0]===1?'A1':x[0]===2?'A2':'B1'}</span><div><b>${x[1]}</b><small>${x[2]}</small></div><span>${x[3]?'›':'🔒'}</span>`;levels.appendChild(b)});const next=Math.min(10,state.done.length+1);$('nextTitle').textContent=`Lliçó ${next} · ${lessons[next].title}`;$('nextSubtitle').textContent=lessons[next].subtitle;$('nextButton').textContent=state.done.includes(next)?'Repetir':'Començar';$('nextButton').onclick=()=>openLesson(next);let list=document.getElementById('lessonList');if(!list){list=document.createElement('section');list.className='lesson-list';list.id='lessonList';levels.parentNode.insertBefore(list,document.querySelector('.next'))}list.innerHTML='<h2 class="section-title">Les teves lliçons</h2><div class="lesson-grid"></div>';const grid=list.querySelector('.lesson-grid');for(let i=1;i<=10;i++){const done=state.done.includes(i),available=i===1||state.done.includes(i-1),b=document.createElement('button');b.className=`lesson-item ${done?'done':''} ${available?'':'locked'}`;b.disabled=!available;b.innerHTML=`<span>${done?'✓':i}</span><div><b>Lliçó ${i} · ${lessons[i].title}</b><small>${lessons[i].subtitle}</small></div><em>${done?'Repetir':available?'Començar':'🔒'}</em>`;if(available)b.onclick=()=>openLesson(i);grid.appendChild(b)}}
function openLesson(id){if(!lessons[id])return;cur={id,i:0,score:0,answered:false};home.classList.add('hidden');lesson.classList.remove('hidden');render();window.scrollTo({top:0,behavior:'smooth'})}
function render(){const l=lessons[cur.id],q=l.questions[cur.i],pct=Math.round(cur.i/l.questions.length*100),label={vocab:'Vocabulari',recall:'Recorda',situation:'Situació'}[q.type];lesson.innerHTML=`<button class="back" id="backLesson">← Tornar al camí</button><div class="lesson-head"><small>A1 · Lliçó ${cur.id}/10 · ${label}</small><span>⭐ ${cur.score}</span></div><div class="progress"><i style="width:${pct}%"></i></div><section class="lesson-card question"><small>${l.subtitle}</small><div class="word">${l.title}</div><p class="objective">${l.objective}</p><div class="question-number">Pregunta ${cur.i+1} de ${l.questions.length}</div><h2>${q.q}</h2><div class="answers" id="answers"></div><div class="feedback" id="feedback" aria-live="polite"></div></section>`;$('backLesson').onclick=goHome;q.a.forEach(option=>{const btn=document.createElement('button');btn.className='answer';btn.textContent=option;btn.onclick=()=>answer(btn,option);$('answers').appendChild(btn)})}
function answer(btn,value){if(cur.answered)return;cur.answered=true;const q=lessons[cur.id].questions[cur.i],fb=$('feedback'),buttons=document.querySelectorAll('.answer');buttons.forEach(b=>b.disabled=true);if(value===q.correct){btn.classList.add('correct');cur.score+=10;fb.textContent='Oso ondo! +10 ⭐';fb.className='feedback good'}else{btn.classList.add('wrong');buttons.forEach(b=>{if(b.textContent===q.correct)b.classList.add('correct')});fb.textContent=`La resposta correcta és «${q.correct}».`;fb.className='feedback bad'}setTimeout(()=>{cur.i++;cur.answered=false;cur.i<lessons[cur.id].questions.length?render():finish()},500)}
function finish(){if(!state.done.includes(cur.id)){state.done.push(cur.id);state.points+=cur.score}const today=new Date().toISOString().slice(0,10);if(state.last!==today){state.streak++;state.last=today}save();lesson.innerHTML=`<section class="lesson-card result"><div class="big">🎉</div><h2>Oso ondo!</h2><p>Lliçó completada: 30 preguntes</p><p>10 vocabulari · 10 recorda · 10 situacions</p><h3>+${cur.score} punts ⭐</h3><p>🔥 Ratxa: ${state.streak} ${state.streak===1?'dia':'dies'}</p><button class="primary" id="repeatLesson">Repetir lliçó</button><button class="back" id="continueHome">← Tornar al camí</button></section>`;$('repeatLesson').onclick=()=>openLesson(cur.id);$('continueHome').onclick=goHome}
function goHome(){lesson.classList.add('hidden');home.classList.remove('hidden');updateHome();window.scrollTo({top:0,behavior:'smooth'})}
updateHome();