const lessons = {
  1:{title:"Kaixo!",subtitle:"Salutacions i comiat",objective:"Aprèn les salutacions bàsiques en euskera.",questions:[["Què vol dir «Kaixo»?",["Hola","Adéu","Gràcies"],"Hola"],["Com diries «Adéu»?",["Kaixo","Agur","Mesedez"],"Agur"],["Quina expressió vol dir «Bon dia»?",["Egun on","Gabon","Laster arte"],"Egun on"],["Què vol dir «Eskerrik asko»?",["Hola","Gràcies","Fins aviat"],"Gràcies"],["Completa: «___ arte!»",["Ikusi","Bai","Ez"],"Ikusi"]]},
  2:{title:"Ni… naiz",subtitle:"Presentar-se",objective:"Aprèn a presentar-te en euskera.",questions:[["Què vol dir «Ni»?",["Jo","Tu","Ell"],"Jo"],["Què vol dir «Zu»?",["Jo","Tu","Nosaltres"],"Tu"],["Completa: «Ni Jon ___»",["naiz","zara","da"],"naiz"]]},
  3:{title:"Bai / Ez",subtitle:"Afirmar i negar",objective:"Aprèn a dir sí i no.",questions:[["Què vol dir «Bai»?",["Sí","No","No ho sé"],"Sí"],["Què vol dir «Ez»?",["Sí","No","D'acord"],"No"],["Com diries «No ho sé»?",["Ados","Ez dakit","Bai"],"Ez dakit"]]},
  4:{title:"Cortesia bàsica",subtitle:"Paraules del dia a dia",objective:"Aprèn expressions bàsiques de cortesia.",questions:[["Com diries «Gràcies»?",["Mesedez","Eskerrik asko","Barkatu"],"Eskerrik asko"],["Què vol dir «Mesedez»?",["Si us plau","Perdó","Benvingut"],"Si us plau"],["Què vol dir «Barkatu»?",["Perdó","Gràcies","Adéu"],"Perdó"]]},
  5:{title:"Repàs!",subtitle:"Mini-joc",objective:"Repassem el que ja saps.",questions:[["Arribes a un lloc. Què pots dir?",["Kaixo","Agur","Barkatu"],"Kaixo"],["Te'n vas. Què pots dir?",["Egun on","Agur","Mesedez"],"Agur"],["Algú t'ajuda. Què dius?",["Eskerrik asko","Ez","Gabon"],"Eskerrik asko"],["Com dius «Si us plau»?",["Barkatu","Mesedez","Agur"],"Mesedez"]]},
  6:{title:"Zenbakiak",subtitle:"Números 1–5",objective:"Comença a comptar en euskera.",questions:[["Què vol dir «bat»?",["Un","Dos","Tres"],"Un"],["Què vol dir «bi»?",["Un","Dos","Quatre"],"Dos"],["Què vol dir «hiru»?",["Tres","Cinc","Dos"],"Tres"]]},
  7:{title:"Etxea",subtitle:"La casa",objective:"Aprèn paraules bàsiques de casa.",questions:[["Què vol dir «etxea»?",["Casa","Carrer","Escola"],"Casa"],["Què vol dir «atea»?",["Finestra","Porta","Taula"],"Porta"],["Què vol dir «leihoa»?",["Finestra","Cadira","Llit"],"Finestra"]]},
  8:{title:"Familia",subtitle:"La família",objective:"Identifica membres de la família.",questions:[["Què vol dir «ama»?",["Pare","Mare","Germà"],"Mare"],["Què vol dir «aita»?",["Pare","Mare","Fill"],"Pare"],["Què vol dir «anaia»?",["Germà","Germana","Àvia"],"Germà"]]},
  9:{title:"Koloreak",subtitle:"Els colors",objective:"Aprèn alguns colors en euskera.",questions:[["Què vol dir «gorria»?",["Blau","Vermell","Verd"],"Vermell"],["Què vol dir «urdina»?",["Blau","Groc","Negre"],"Blau"],["Què vol dir «berdea»?",["Verd","Blanc","Vermell"],"Verd"]]},
  10:{title:"Egunerokoa",subtitle:"El dia a dia",objective:"Posa en pràctica el vocabulari après.",questions:[["Què vol dir «gaur»?",["Avui","Demà","Ahir"],"Avui"],["Què vol dir «bihar»?",["Avui","Demà","Ara"],"Demà"],["Què vol dir «orain»?",["Després","Ara","Sempre"],"Ara"]]}
};
const levelNames={1:["A1 · Hasiberria","Comença des de zero"],2:["A2 · Intermedi","Desbloqueja completant A1"],3:["B1 · Intermedi avançat","Desbloqueja completant A2"]};
let state=JSON.parse(localStorage.getItem("kaixoState")||'{"points":0,"done":[],"streak":0,"last":""}');
let cur=null; const $=id=>document.getElementById(id); const home=$("home"),lesson=$("lesson");
function save(){localStorage.setItem("kaixoState",JSON.stringify(state));updateHome()}
function updateHome(){
  $("points").textContent=state.points;$("done").textContent=state.done.length;$("streak").textContent=state.streak;
  const levels=$("levels"); levels.innerHTML="";
  [[1,"A1 · Hasiberria","Comença des de zero · 10 lliçons",true],[2,"A2 · Intermedi","Desbloqueja completant A1",state.done.length>=10],[3,"B1 · Intermedi avançat","Desbloqueja completant A2",false]].forEach(x=>{
    const b=document.createElement("button"); b.className="level-card "+(x[3]?"active":"locked"); b.disabled=!x[3]; b.innerHTML=`<span class="badge">${x[0]===1?'A1':x[0]===2?'A2':'B1'}</span><div><b>${x[1]}</b><small>${x[2]}</small></div><span>${x[3]?'›':'🔒'}</span>`; if(x[3])b.onclick=()=>openLesson(Math.max(1,state.done.length+1)); levels.appendChild(b);
  });
  const next=Math.min(10,state.done.length+1); $("nextTitle").textContent=`Lliçó ${next} · ${lessons[next].title}`;$("nextSubtitle").textContent=lessons[next].subtitle;$("nextButton").onclick=()=>openLesson(next);
}
function openLesson(id){if(!lessons[id])return;cur={id,i:0,score:0,answered:false};home.classList.add("hidden");lesson.classList.remove("hidden");render();window.scrollTo({top:0,behavior:"smooth"})}
function render(){const l=lessons[cur.id],q=l.questions[cur.i],pct=Math.round(cur.i/l.questions.length*100);lesson.innerHTML=`<button class="back" id="backLesson">← Tornar</button><div class="lesson-head"><small>A1 · Lliçó ${cur.id}/10</small><span>⭐ ${cur.score}</span></div><div class="progress"><i style="width:${pct}%"></i></div><section class="lesson-card question"><small>${l.subtitle}</small><div class="word">${l.title}</div><p class="objective">${l.objective}</p><div class="question-number">Pregunta ${cur.i+1} de ${l.questions.length}</div><h2>${q[0]}</h2><div class="answers" id="answers"></div><div class="feedback" id="feedback" aria-live="polite"></div></section>`;$("backLesson").onclick=goHome;q[1].forEach(option=>{const btn=document.createElement("button");btn.className="answer";btn.textContent=option;btn.onclick=()=>answer(btn,option);$("answers").appendChild(btn)})}
function answer(btn,value){if(cur.answered)return;cur.answered=true;const q=lessons[cur.id].questions[cur.i],fb=$("feedback"),buttons=document.querySelectorAll(".answer");buttons.forEach(b=>b.disabled=true);if(value===q[2]){btn.classList.add("correct");cur.score+=10;fb.textContent="Oso ondo! +10 ⭐";fb.className="feedback good"}else{btn.classList.add("wrong");buttons.forEach(b=>{if(b.textContent===q[2])b.classList.add("correct")});fb.textContent=`La resposta correcta és «${q[2]}».`;fb.className="feedback bad"}setTimeout(()=>{cur.i++;cur.answered=false;cur.i<lessons[cur.id].questions.length?render():finish()},850)}
function finish(){if(!state.done.includes(cur.id)){state.done.push(cur.id);state.points+=cur.score}const today=new Date().toISOString().slice(0,10);if(state.last!==today){state.streak++;state.last=today}save();lesson.innerHTML=`<section class="lesson-card result"><div class="big">🎉</div><h2>Oso ondo!</h2><p>Lliçó completada</p><h3>+${cur.score} punts ⭐</h3><p>🔥 Ratxa: ${state.streak} ${state.streak===1?'dia':'dies'}</p><button class="primary" id="continueHome">Continuar</button></section>`;$("continueHome").onclick=goHome}
function goHome(){lesson.classList.add("hidden");home.classList.remove("hidden");updateHome();window.scrollTo({top:0,behavior:"smooth"})}
updateHome();
