const bank={
1:{title:"Kaixo!",subtitle:"Salutacions i comiat",objective:"Domina les salutacions i expressions bàsiques.",words:[["Kaixo","Hola"],["Agur","Adéu"],["Egun on","Bon dia"],["Arratsalde on","Bona tarda"],["Gabon","Bona nit"],["Eskerrik asko","Gràcies"],["Mesedez","Si us plau"],["Barkatu","Perdó"],["Ikusi arte","Fins aviat"],["Ongi etorri","Benvingut"]]},
2:{title:"Ni… naiz",subtitle:"Presentar-se",objective:"Aprèn a dir qui ets i a preguntar pel nom.",words:[["Ni","Jo"],["Zu","Tu"],["Hura","Ell/ella"],["Gu","Nosaltres"],["Zuek","Vosaltres"],["Nor","Qui"],["Zer","Què"],["Izena","Nom"],["Naiz","Soc"],["Zara","Ets"]]},
3:{title:"Bai / Ez",subtitle:"Afirmar i negar",objective:"Aprèn a respondre sí, no i expressions habituals.",words:[["Bai","Sí"],["Ez","No"],["Ez dakit","No ho sé"],["Agian","Potser"],["Ados","D'acord"],["Noski","És clar"],["Egia","Veritat"],["Oker","Incorrecte"],["Bada","Doncs sí"],["Ez da","No és"]]},
4:{title:"Cortesia bàsica",subtitle:"Paraules del dia a dia",objective:"Utilitza expressions de cortesia amb naturalitat.",words:[["Eskerrik asko","Gràcies"],["Mila esker","Moltes gràcies"],["Mesedez","Si us plau"],["Barkatu","Perdó"],["Aizu","Escolta / Ei"],["Ongi","Bé"],["Oso ondo","Molt bé"],["Ez horregatik","De res"],["Barkatu, mesedez","Perdona, si us plau"],["Agur bero bat","Una salutació afectuosa"]]},
5:{title:"Repàs!",subtitle:"Situacions quotidianes",objective:"Aplica el que has après en situacions reals.",words:[["Kaixo","Hola"],["Agur","Adéu"],["Eskerrik asko","Gràcies"],["Mesedez","Si us plau"],["Barkatu","Perdó"],["Bai","Sí"],["Ez","No"],["Egun on","Bon dia"],["Gabon","Bona nit"],["Ongi etorri","Benvingut"]]},
6:{title:"Zenbakiak",subtitle:"Números 1–10",objective:"Aprèn els primers números en euskera.",words:[["bat","1"],["bi","2"],["hiru","3"],["lau","4"],["bost","5"],["sei","6"],["zazpi","7"],["zortzi","8"],["bederatzi","9"],["hamar","10"]]},
7:{title:"Etxea",subtitle:"La casa",objective:"Aprèn vocabulari essencial de la llar.",words:[["etxea","Casa"],["atea","Porta"],["leihoa","Finestra"],["mahaia","Taula"],["aulkia","Cadira"],["ohea","Llit"],["sukaldea","Cuina"],["bainugela","Bany"],["egongela","Sala d'estar"],["gela","Habitació"]]},
8:{title:"Familia",subtitle:"La família",objective:"Identifica els membres de la família.",words:[["ama","Mare"],["aita","Pare"],["anaia","Germà"],["arreba","Germana"],["semea","Fill"],["alaba","Filla"],["amona","Àvia"],["aitona","Avi"],["osaba","Oncle"],["izeba","Tieta"]]},
9:{title:"Koloreak",subtitle:"Els colors",objective:"Aprèn els colors més habituals.",words:[["gorria","Vermell"],["urdina","Blau"],["berdea","Verd"],["horia","Groc"],["beltza","Negre"],["zuria","Blanc"],["laranja","Taronja"],["morea","Lila"],["arrosa","Rosa"],["marroia","Marró"]]},
10:{title:"Egunerokoa",subtitle:"El dia a dia",objective:"Parla de temps, moments i accions quotidianes.",words:[["gaur","Avui"],["bihar","Demà"],["atzo","Ahir"],["orain","Ara"],["gero","Després"],["goizean","Al matí"],["arratsaldean","A la tarda"],["gauean","A la nit"],["beti","Sempre"],["inoiz ez","Mai"]]}
};
function makeQuestions(words){
 const out=[];
 const pool=words.map(x=>x[1]);
 words.forEach(([eu,ca],i)=>{const d1=pool[(i+1)%pool.length],d2=pool[(i+2)%pool.length];out.push([`Què vol dir «${eu}»?`,[ca,d1,d2],ca]);});
 words.forEach(([eu,ca],i)=>{const d1=words[(i+1)%words.length][0],d2=words[(i+2)%words.length][0];out.push([`Com es diu «${ca}» en euskera?`,[eu,d1,d2],eu]);});
 words.forEach(([eu,ca],i)=>{const d1=pool[(i+3)%pool.length],d2=pool[(i+4)%pool.length];out.push([`Tria el significat correcte de «${eu}».`,[d1,ca,d2],ca]);});
 return out;
}
const lessons=Object.fromEntries(Object.entries(bank).map(([id,l])=>[id,{...l,questions:makeQuestions(l.words)}]));
const levelNames={1:["A1 · Hasiberria","Comença des de zero"],2:["A2 · Intermedi","Desbloqueja completant A1"],3:["B1 · Intermedi avançat","Desbloqueja completant A2"]};
let state=JSON.parse(localStorage.getItem("kaixoState")||'{"points":0,"done":[],"streak":0,"last":""}');
let cur=null;const $=id=>document.getElementById(id),home=$("home"),lesson=$("lesson");
function save(){localStorage.setItem("kaixoState",JSON.stringify(state));updateHome()}
function updateHome(){
 $("points").textContent=state.points;$("done").textContent=state.done.length;$("streak").textContent=state.streak;
 const levels=$("levels");levels.innerHTML="";
 [[1,"A1 · Hasiberria","10 lliçons · 300 preguntes",true],[2,"A2 · Intermedi","Desbloqueja completant A1",state.done.length>=10],[3,"B1 · Intermedi avançat","Desbloqueja completant A2",false]].forEach(x=>{const b=document.createElement("button");b.className="level-card "+(x[3]?"active":"locked");b.disabled=!x[3];b.innerHTML=`<span class="badge">${x[0]===1?'A1':x[0]===2?'A2':'B1'}</span><div><b>${x[1]}</b><small>${x[2]}</small></div><span>${x[3]?'›':'🔒'}</span>`;levels.appendChild(b)});
 const next=Math.min(10,state.done.length+1);$("nextTitle").textContent=`Lliçó ${next} · ${lessons[next].title}`;$("nextSubtitle").textContent=lessons[next].subtitle;$("nextButton").textContent=state.done.includes(next)?"Repetir":"Començar";$("nextButton").onclick=()=>openLesson(next);
 let list=document.getElementById("lessonList");if(!list){list=document.createElement("section");list.className="lesson-list";list.id="lessonList";levels.parentNode.insertBefore(list,document.querySelector(".next"));}
 list.innerHTML='<h2 class="section-title">Les teves lliçons</h2><div class="lesson-grid"></div>';
 const grid=list.querySelector(".lesson-grid");for(let i=1;i<=10;i++){const done=state.done.includes(i),available=i===1||state.done.includes(i-1);const b=document.createElement("button");b.className=`lesson-item ${done?'done':''} ${available?'':'locked'}`;b.disabled=!available;b.innerHTML=`<span>${done?'✓':i}</span><div><b>Lliçó ${i} · ${lessons[i].title}</b><small>${lessons[i].subtitle}</small></div><em>${done?'Repetir':available?'Començar':'🔒'}</em>`;if(available)b.onclick=()=>openLesson(i);grid.appendChild(b)}
}
function openLesson(id){if(!lessons[id])return;cur={id,i:0,score:0,answered:false};home.classList.add("hidden");lesson.classList.remove("hidden");render();window.scrollTo({top:0,behavior:"smooth"})}
function render(){const l=lessons[cur.id],q=l.questions[cur.i],pct=Math.round(cur.i/l.questions.length*100);lesson.innerHTML=`<button class="back" id="backLesson">← Tornar al camí</button><div class="lesson-head"><small>A1 · Lliçó ${cur.id}/10</small><span>⭐ ${cur.score}</span></div><div class="progress"><i style="width:${pct}%"></i></div><section class="lesson-card question"><small>${l.subtitle}</small><div class="word">${l.title}</div><p class="objective">${l.objective}</p><div class="question-number">Pregunta ${cur.i+1} de ${l.questions.length}</div><h2>${q[0]}</h2><div class="answers" id="answers"></div><div class="feedback" id="feedback" aria-live="polite"></div></section>`;$("backLesson").onclick=goHome;q[1].forEach(option=>{const btn=document.createElement("button");btn.className="answer";btn.textContent=option;btn.onclick=()=>answer(btn,option);$("answers").appendChild(btn)})}
function answer(btn,value){if(cur.answered)return;cur.answered=true;const q=lessons[cur.id].questions[cur.i],fb=$("feedback"),buttons=document.querySelectorAll(".answer");buttons.forEach(b=>b.disabled=true);if(value===q[2]){btn.classList.add("correct");cur.score+=10;fb.textContent="Oso ondo! +10 ⭐";fb.className="feedback good"}else{btn.classList.add("wrong");buttons.forEach(b=>{if(b.textContent===q[2])b.classList.add("correct")});fb.textContent=`La resposta correcta és «${q[2]}».`;fb.className="feedback bad"}setTimeout(()=>{cur.i++;cur.answered=false;cur.i<lessons[cur.id].questions.length?render():finish()},500)}
function finish(){if(!state.done.includes(cur.id)){state.done.push(cur.id);state.points+=cur.score}const today=new Date().toISOString().slice(0,10);if(state.last!==today){state.streak++;state.last=today}save();lesson.innerHTML=`<section class="lesson-card result"><div class="big">🎉</div><h2>Oso ondo!</h2><p>Lliçó completada: 30 preguntes</p><h3>+${cur.score} punts ⭐</h3><p>🔥 Ratxa: ${state.streak} ${state.streak===1?'dia':'dies'}</p><button class="primary" id="repeatLesson">Repetir lliçó</button><button class="back" id="continueHome">← Tornar al camí</button></section>`;$("repeatLesson").onclick=()=>openLesson(cur.id);$("continueHome").onclick=goHome}
function goHome(){lesson.classList.add("hidden");home.classList.remove("hidden");updateHome();window.scrollTo({top:0,behavior:"smooth"})}
updateHome();
